#!/usr/bin/env python3
"""
hook_generator.py -- Portable Git hooks template generator.
Renders Windows/Linux absolute paths via --install-dir; zero hard-coded machine paths.

Usage (Linux):   python hook_generator.py --install-dir /home/user/repo --platform linux
Usage (Windows): python hook_generator.py --install-dir C:\\Users\\user\\repo --platform windows
Dry-run:         python hook_generator.py --install-dir /path/to/repo --dry-run
"""
import argparse
import pathlib
import platform
import stat
import textwrap

TEMPLATES_LINUX = {
    "pre-commit": """#!/bin/sh
# pre-commit -- generated by hook_generator.py (linux)
REPO_ROOT="{repo_root}"
VENV_PYTHON="{venv_python}"
cd "$REPO_ROOT" || exit 1
if [ -f "$VENV_PYTHON" ]; then
    "$VENV_PYTHON" -m flake8 . --count --select=E9,F63,F7,F82 --show-source
else
    echo "[pre-commit] venv not found, skipping lint"
fi
""",
    "commit-msg": """#!/bin/sh
# commit-msg -- generated by hook_generator.py (linux)
MSG_FILE="$1"
if ! grep -qE "^(feat|fix|docs|style|refactor|test|chore)(\\(.+\\))?: .+" "$MSG_FILE"; then
    echo "[commit-msg] message does not follow Conventional Commits" >&2
    exit 1
fi
""",
    "pre-push": """#!/bin/sh
# pre-push -- generated by hook_generator.py (linux)
REPO_ROOT="{repo_root}"
VENV_PYTHON="{venv_python}"
cd "$REPO_ROOT" || exit 1
if [ -f "$VENV_PYTHON" ]; then
    "$VENV_PYTHON" -m pytest --tb=short -q
else
    echo "[pre-push] venv not found, skipping tests"
fi
""",
    "install-deps": """#!/bin/sh
# install-deps -- generated by hook_generator.py (linux)
REPO_ROOT="{repo_root}"
VENV_DIR="{venv_dir}"
REQ_FILE="{req_file}"
cd "$REPO_ROOT" || exit 1
[ -d "$VENV_DIR" ] || python3 -m venv "$VENV_DIR"
"$VENV_DIR/bin/pip" install -q -r "$REQ_FILE"
echo "[install-deps] deps installed to $VENV_DIR"
""",
}

TEMPLATES_WINDOWS = {
    "pre-commit.cmd": """@echo off
REM pre-commit -- generated by hook_generator.py (windows)
set REPO_ROOT={repo_root}
set VENV_PYTHON={venv_python}
cd /d "%REPO_ROOT%" || exit /b 1
if exist "%VENV_PYTHON%" (
    "%VENV_PYTHON%" -m flake8 . --count --select=E9,F63,F7,F82 --show-source
) else (
    echo [pre-commit] venv not found, skipping lint
)
""",
    "commit-msg.cmd": """@echo off
REM commit-msg -- generated by hook_generator.py (windows)
set MSG_FILE=%1
findstr /R "^feat\\|^fix\\|^docs\\|^style\\|^refactor\\|^test\\|^chore" "%MSG_FILE%" >nul 2>&1
if errorlevel 1 (
    echo [commit-msg] message does not follow Conventional Commits 1>&2
    exit /b 1
)
""",
    "pre-push.cmd": """@echo off
REM pre-push -- generated by hook_generator.py (windows)
set REPO_ROOT={repo_root}
set VENV_PYTHON={venv_python}
cd /d "%REPO_ROOT%" || exit /b 1
if exist "%VENV_PYTHON%" (
    "%VENV_PYTHON%" -m pytest --tb=short -q
) else (
    echo [pre-push] venv not found, skipping tests
)
""",
    "install-deps.cmd": """@echo off
REM install-deps -- generated by hook_generator.py (windows)
set REPO_ROOT={repo_root}
set VENV_DIR={venv_dir}
set REQ_FILE={req_file}
cd /d "%REPO_ROOT%" || exit /b 1
if not exist "%VENV_DIR%" python -m venv "%VENV_DIR%"
"%VENV_DIR%\\Scripts\\pip" install -q -r "%REQ_FILE%"
echo [install-deps] deps installed to %VENV_DIR%
""",
}


def resolve_platform(arg):
    if arg == "auto":
        return "windows" if platform.system() == "Windows" else "linux"
    return arg.lower()


def build_paths(install_dir, plat, venv_dir, req_file):
    p = pathlib.Path(install_dir).resolve()
    if plat == "windows":
        return {
            "repo_root": str(p),
            "venv_python": str(p / venv_dir / "Scripts" / "python.exe"),
            "venv_dir": str(p / venv_dir),
            "req_file": str(p / req_file),
        }
    return {
        "repo_root": str(p),
        "venv_python": str(p / venv_dir / "bin" / "python"),
        "venv_dir": str(p / venv_dir),
        "req_file": str(p / req_file),
    }


def generate_hooks(args):
    plat = resolve_platform(args.platform)
    paths = build_paths(args.install_dir, plat, args.venv_dir, args.req_file)
    hooks_dir = pathlib.Path(args.install_dir).resolve() / args.hooks_dir
    tpl_set = TEMPLATES_WINDOWS if plat == "windows" else TEMPLATES_LINUX
    results = []
    for name, tpl in tpl_set.items():
        content = tpl.format(**paths)
        out_path = hooks_dir / name
        if args.dry_run:
            print(f"[dry-run] {out_path}")
            print(textwrap.indent(content, "  "))
            results.append(str(out_path))
            continue
        hooks_dir.mkdir(parents=True, exist_ok=True)
        if out_path.exists() and not args.overwrite:
            print(f"[skip] {out_path} already exists (use --overwrite)")
            continue
        out_path.write_text(content, encoding="utf-8")
        if plat != "windows":
            out_path.chmod(out_path.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)
        print(f"[ok] {out_path}")
        results.append(str(out_path))
    return results


def main():
    parser = argparse.ArgumentParser(
        description="Portable Git hooks generator. Renders Windows/Linux absolute paths from install parameters."
    )
    parser.add_argument("--install-dir", required=True)
    parser.add_argument("--platform", default="auto", choices=["auto", "windows", "linux"])
    parser.add_argument("--hooks-dir", default=".git/hooks")
    parser.add_argument("--venv-dir", default=".venv")
    parser.add_argument("--req-file", default="requirements.txt")
    parser.add_argument("--overwrite", action="store_true")
    parser.add_argument("--dry-run", action="store_true")
    generate_hooks(parser.parse_args())


if __name__ == "__main__":
    main()
